spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_sql
    password: QWERTY00qwerty00
    username: root
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect