INSERT INTO public.subject (name,tutor) VALUES ('Compucter science','Pips');
INSERT INTO public.subject (name,tutor) VALUES ('Relational databases','Mykhailo Golovachov');
INSERT INTO public.subject (name,tutor) VALUES ('Microservices architecture','Roman Kovalchuk');
INSERT INTO public.subject (name,tutor) VALUES ('Web frontend development','Ivan Bulavko');
INSERT INTO public.subject (name,tutor) VALUES ('Web backend development','Roman Kovalchuk');
INSERT INTO public.subject (name,tutor) VALUES ('Cloud development','Ruslan Gumeniyk');
INSERT INTO public.subject (name,tutor) VALUES ('Unit testing','Kyrylo Gerasymenko');
INSERT INTO public.subject (name,tutor) VALUES ('Android development','Andriy Pedosenko');
INSERT INTO public.subject (name,tutor) VALUES ('No SQL databases','Hlib Kizin');
INSERT INTO public.subject (name,tutor) VALUES ('UX/UI designing','Oleg Yavorsky');
